### ISSUE TITLE
What do the bigger red and green circles represent in the video?

### ISSUE THREAD

**Issue by zhangj726** [husikl/asar_hqp_endoscope#1]
hi, thanks for your work.  I wanna know what bigger red and green circles, which are shown in Fig. 8 in the paper as well, represent in the supplementary video. I have read the paper, but no detailed explanation was found.
![image](https://github.com/husikl/asar_hqp_endoscope/assets/148530302/ac1b0180-59ea-46a4-92fb-d27d021a3637)

**Comment by husikl** [comment]
Hello and sorry for late reply. The circles correspond to the ROI. The center of the ROI is then given as a target for the robot to position the endoscope. You can take a look at the scripts/dynamic_roi.py the script computes and displays the circles. The difference between the green and red one is that that the red one is computed using mean filter.

**Comment by zhangj726** [comment]
Thanks for your kindly reply. 
Best wishes.
