### ISSUE TITLE
"The 'segment_anything' folder is missing

### ISSUE THREAD

**Issue by Chenyang0124** [husikl/asar_hqp_endoscope#2]
Hello, I've noticed that there is no Python file in the directory asar_hqp_endoscope-main\interact_seg_track_ros\segment-anything. However, the main.py script references libraries from this folder, which is causing the project to fail. Could you please provide the contents of this folder? It appears to be missing and is essential for the project to run properly. Thank you
![Uploading 屏幕截图 2024-10-13 153825.png…]()

**Comment by husikl** [comment]
Hello!

I've implemented a standalone package called **`ist_ros`**, which you can find here: [ist_ros GitHub repository](https://github.com/husikl/ist_ros.git). This package will be updated, with a focus on CoppeliaSim-based simulation to demonstrate the **HQP**-based control.

To use the **`interact_seg_track_ros`** package, you'll need to install the **`segment-anything`** library from [Facebook Research's repository](https://github.com/facebookresearch/segment-anything). However, I recommend trying the **`ist_ros`** package, as it offers the same performance but with a better GUI and improved documentation.

I'll be restructuring **`interact_seg_track_ros`** soon. The main difference between the two packages is that **`ist_ros`** publishes image masks and barycenters as **NumPy** arrays for easier data extraction, whereas **`interact_seg_track_ros`** publishes a **`PoseArray`** for tool tracking, where:

- `geometry_msgs/Pose p`: `x` and `y` correspond to the pixel position, and `z` corresponds to the minimum enclosing circle radius.
- `p.orientation.x` can take values `1` or `-1` to differentiate cases when the tool is temporarily lost.

Additionally, **`interact_seg_track_ros`** includes an ROI estimator in **`dynamic_roi.py`** to estimate how to position the endoscopic camera based on the ROI's center. You can see more details in the [paper](https://www.mdpi.com/1424-8220/23/24/9865). I'll be providing documentation for this package soon. Let me know if you have any further questions!

**Comment by Chenyang0124** [comment]
Hello!

Thank you for your detailed response and for sharing information about the ist_ros package and its features. If I have any further questions or need assistance, I'll definitely reach out. Thanks again for your help!
